### ISSUE TITLE
Wrong import of pybel

### ISSUE THREAD

**Issue by TimoSommer** [hachmannlab/chemml#10]
In the module chemml.chem.magpie_python.CompositionEntry there is one line saying "import pybel". However, in the new version of openbabel, this syntax is no longer supported and it must read "from openbabel import pybel" insteaf, see here: https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html

**Comment by aditya1707** [comment]
Hi, 

At this time, ChemML works with an older version of Openbabel (i.e., Openbabel 2). We are working on upgrades and will bring it up to speed soon. 

Thank you for your patience.
